### ISSUE TITLE
Don't work in case of function in different class

### ISSUE THREAD

**Issue by shahriyardx** [Gelbpunkt/aioscheduler#2]
So I have a function in my bot class which a subclass of AutoShardedBot and the function is remove_role_task

When I try to start a job from a cog using schedule method and the coro is like bot.remove_role_task the task never starts. And when I check the tasks of the scheduler its empty. But when I create the same method in the cog itself the task starts and executes in time.

**Comment by Gelbpunkt** [comment]
Hi, can you send me an example so I can reproduce this issue locally? This seems a bit weird

**Comment by shahriyardx** [comment]
Actually no. I found the issue. So when I pass a invalid argument on the coro the task executes but does not show any error. I guess that was my case.
